from os.path import join

rule extract_sample_metadata:
    input:
        join("data", "E-MTAB-5061.sdrf.txt")
    output:
        join("output", "samples.tsv"),
        join("output", "patients.tsv")
    shell:
        "python src/extract_metadata.py"
