


rule extract_sample_metadata:
    input:
        "data/celltype_annotation.tsv",
        "data/sample.tsv",
        "data/participant.tsv"
    output:
        "output/patients.tsv",
        "output/samples.tsv"
    script:
        "src/extract_sample_metadata.py"
