from os.path import join
import pandas as pd
from snakemake.utils import min_version
##### set minimum snakemake version #####
min_version("5.1.2")

##### load config and sample sheets #####
configfile: "config/PathSeq-config.yaml"


# patients = pd.read_csv(config["patients"], sep="\t").set_index("patient", drop=False)
# validate(samples, schema="schemas/samples.schema.yaml")
lanes = pd.read_csv(config["samples"], dtype=str, sep="\t").set_index(["patient", "sample", "lane"], drop=False)
lanes.index = lanes.index.set_levels([i.astype(str) for i in lanes.index.levels])  # enforce str in index
samples = lanes[["sample", "patient"]].drop_duplicates()

cells = pd.read_csv(config["units"], sep="\t").set_index(["sample", "barcode", "patient"], drop=False)

wildcard_constraints:
    patient="P1",
    sample="|".join(lanes["sample"].unique()),
    lane="|".join(lanes["lane"].unique())

# Snakemake includes
include: "../RNA-snakemake-rules/rules/cellranger.smk"

# Directories
FASTQ_DIR = "FASTQ"
PATIENT_FASTQ_DIR = join("FASTQ", "raw", "{patient}")
CR_SAMPLE_ODIR = "{patient}-{sample}"

# STAR Input Files
SRA_FASTQ1_FILE = join(FASTQ_DIR, "{run}_1.fastq")
SRA_FASTQ2_FILE = join(FASTQ_DIR, "{run}_2.fastq")

# CellRanger Files
CB_FASTQ_FILE = join(PATIENT_FASTQ_DIR, "{sample}_{lane}_R1_001.fastq.gz")
cDNA_FASTQ_FILE = join(PATIENT_FASTQ_DIR, "{sample}_{lane}_R2_001.fastq.gz")
CR_BAM_FILE = join(CR_SAMPLE_ODIR, "outs", "possorted_genome_bam.bam")

CB_SAMPLE_FASTQ_FILE = join(PATIENT_FASTQ_DIR, "{sample}_R1_001.fastq.gz")
cDNA_SAMPLE_FASTQ_FILE = join(PATIENT_FASTQ_DIR, "{sample}_R2_001.fastq.gz")


### rules to download FASTQ files ###

rule download_FASTQ_from_SRA:
    group:
        "FASTQ"
    conda:
        "../envs/sratoolkit-env.yaml"
    params:
        FASTQ_DIR
    output:
        SRA_FASTQ1_FILE,
        SRA_FASTQ2_FILE
    shell:
        "prefetch {wildcards.run} \n"
        "fasterq-dump --mem 16000M -O {params} -t temp/ --include-technical --split-files {wildcards.run} \n"

def get_sra_fq_files(wildcards):
    run_of_interest = lanes.loc[(lanes["patient"] == wildcards.patient) & (lanes["sample"] ==  wildcards.sample) & (lanes["lane"] ==  wildcards.lane), "Run"]
    return {
        "CellBarcode_fq": expand(SRA_FASTQ1_FILE, run=run_of_interest),
        "cDNA_fq": expand(SRA_FASTQ2_FILE, run=run_of_interest),
    }

# compress and rename
rule compress_rename_SRA_FASTQ_files:
    group:
        "FASTQ"
    input:
        unpack(get_sra_fq_files)
    output:
        CellBarcode_fq = CB_FASTQ_FILE,
        cDNA_fq = cDNA_FASTQ_FILE,
    shell:
        "ml pigz/2.7-GCCcore-11.3.0 && "
        "pigz -p 4 -c {input.CellBarcode_fq} > {output.CellBarcode_fq} && "
        "pigz -p 4 -c {input.cDNA_fq} > {output.cDNA_fq}"

def get_sra_fq_files_by_sample(wildcards):
    runs_of_interest = lanes.loc[(lanes["patient"] == wildcards.patient) & (lanes["sample"] ==  wildcards.sample), "Run"]
    return {
        "CellBarcode_fq": expand(SRA_FASTQ1_FILE, run=runs_of_interest),
        "cDNA_fq": expand(SRA_FASTQ2_FILE, run=runs_of_interest),
    }





