from os.path import join


SRA_RUN_TABLE = join("data", "SraRunTable.csv")
PATIENT_FILE = join("output", "patients.tsv")
SAMPLE_FILE = join("output", "samples.tsv")

rule extract_patient_sample_information:
    input:
        SRA_RUN_TABLE
    output:
        PATIENT_FILE,
        SAMPLE_FILE
    script:
        "src/extract_patient_sample.py"
