

rule extract_sample_metadata:
    input:
        "data/SraRunTable.txt"
    output:
        "output/samples.tsv",
        "output/patients.tsv"
    shell:
        "python src/extract_sample_metadata.py"
